export const europeanCountries = [
  { id: "albania", name: "Albánia" },
  { id: "andorra", name: "Andorra" },
  { id: "austria", name: "Ausztria" },
  { id: "belarus", name: "Fehéroroszország" },
  { id: "belgium", name: "Belgium" },
  { id: "bosniaAndHerzegovina", name: "Bosznia-Hercegovina" },
  { id: "bulgaria", name: "Bulgária" },
  { id: "croatia", name: "Horvátország" },
  { id: "cyprus", name: "Ciprus" },
  { id: "czechRepublic", name: "Csehország" },
  { id: "denmark", name: "Dánia" },
  { id: "unitedKingdom", name: "Egyesült Királyság" },
  { id: "estonia", name: "Észtország" },
  { id: "finland", name: "Finnország" },
  { id: "france", name: "Franciaország" },
  { id: "germany", name: "Németország" },
  { id: "greece", name: "Görögország" },
  { id: "hungary", name: "Magyarország" },
  { id: "iceland", name: "Izland" },
  { id: "ireland", name: "Írország" },
  { id: "italy", name: "Olaszország" },
  { id: "latvia", name: "Lettország" },
  { id: "liechtenstein", name: "Liechtenstein" },
  { id: "lithuania", name: "Litvánia" },
  { id: "luxembourg", name: "Luxemburg" },
  { id: "malta", name: "Málta" },
  { id: "moldova", name: "Moldova" },
  { id: "monaco", name: "Monaco" },
  { id: "montenegro", name: "Montenegró" },
  { id: "netherlands", name: "Hollandia" },
  { id: "northMacedonia", name: "Észak-Macedónia" },
  { id: "norway", name: "Norvégia" },
  { id: "poland", name: "Lengyelország" },
  { id: "portugal", name: "Portugália" },
  { id: "romania", name: "Románia" },
  { id: "russia", name: "Oroszország" },
  { id: "sanMarino", name: "San Marino" },
  { id: "serbia", name: "Szerbia" },
  { id: "slovakia", name: "Szlovákia" },
  { id: "slovenia", name: "Szlovénia" },
  { id: "spain", name: "Spanyolország" },
  { id: "sweden", name: "Svédország" },
  { id: "switzerland", name: "Svájc" },
  { id: "ukraine", name: "Ukrajna" },
];
